# Generated by Django 3.1.6 on 2021-03-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_auto_20210305_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='code',
            field=models.CharField(default='12345678', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='opt1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='opt2',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='opt3',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='opt4',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=2000),
        ),
    ]
