# Generated by Django 3.1.6 on 2021-02-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_quizzes'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
