# Generated by Django 3.1.6 on 2021-02-25 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_questions_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='published_date',
        ),
    ]
