# Generated by Django 3.1.3 on 2021-02-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_remove_questions_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='quizy', to='quizapp.Questions'),
        ),
    ]
