# Generated by Django 3.1.3 on 2021-02-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_auto_20210225_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='quizzy', to='quizapp.Questions'),
        ),
    ]
